{{- with .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace  }}
  {{ if hasKey . "Annotations" }}
  {{ with .Annotations.deployment }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
  {{ end}}
spec:
  replicas: {{ .replicaCount }}
  revisionHistoryLimit: {{ $.Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "kong.deploymentSelectorLabels" $ | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .maxSurge }}
      maxUnavailable: {{ .maxUnavailable }}
    type: {{ .type }}
  template:
    metadata:
    {{ if hasKey . "Annotations" }}
    {{- with .Annotations.pod }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{ end }}
      labels:
        {{- include "kong.podSelectorLabels" $ | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .securityContext }}
      # initContainers:
      #   - command:
      #     - /bin/chown
      #     - -R
      #     - "1001:1001"
      #     - /usr/local/kong
      #     image: debian:latest
      #     name: init-kong
      # securityContext:
      #   runAsUser: 1001
      #   runAsGroup: 1001
      #   fsGroup: 1001
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
      containers:
        {{- range $containers := .containers }}
        - name: {{ $containers.name }}
          # command:
          # - /usr/local/bin/kong migrations bootstrap
          image: "{{ $.Values.deployment.repositoryUrl }}"
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          ports:
          {{- range $ports := $containers.ports }}
          - containerPort: {{ $ports.containerPort }}
            protocol: {{ $ports.protocol }}
          {{- end }}
          {{ if hasKey $containers "secrets" }}
          {{ if $containers.secrets.enabled }}
          envFrom:
          - secretRef:
              name: {{ $.Release.Name }}-secret
          {{ end }}
          {{ end }}
          {{- with $containers.env }}
          env:
            {{- include "kong.defaultEnvVars" $ | nindent 12 }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ if $containers.healthcheck.enabled }}
          {{ if hasKey $containers.healthcheck "exec" }}
          {{- include "kong.healthCheckExec" $containers | nindent 10 }}
          {{ else }}
          {{- include "kong.healthCheck" $containers | nindent 10 }}
          {{ end }}
          {{ end }}
          {{ with $containers.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          {{ if hasKey $containers "volumeMounts" }}
          {{- with $containers.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{ end }}
          {{ if hasKey $containers "lifecycle" }}
          {{ with $containers.lifecycle }}
          lifecycle:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          {{ end }}
        {{- end  }}
     
      {{- with .volumes }}
      volumes:
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{ end }}
