apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "kong.deploymentSelectorLabels" . | nindent 4 }}
  type: ClusterIP
